// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://dsnimoewqcyeegvedion.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzbmltb2V3cWN5ZWVndmVkaW9uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2MzQ2MzQsImV4cCI6MjA3ODIxMDYzNH0.mPO_t1dxPMMx_3ExfkiDEV2wYSyV3OyLj1RhbMFt9I8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);