"use client";

import React, { useEffect, useState } from "react";
import { useRouter, usePathname } from "next/navigation";
// REMOVED: duplicate createClient imports and incorrect local client import
// import { createClient } from "@supabase/supabase-js";
// import supabase from "./client";
// This file is automatically generated. Do not edit it directly.
// import { createClient } from '@supabase/supabase-js';
// const SUPABASE_URL = "https://dsnimoewqcyeegvedion.supabase.co";
// const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzbmltb2V3cWN5ZWVndmVkaW9uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2MzQ2MzQsImV4cCI6MjA3ODIxMDYzNH0.mPO_t1dxPMMx_3ExfkiDEV2wYSyV3OyLj1RhbMFt9I8";

// UPDATED: use the shared Supabase client
import { supabase } from "@/integrations/supabase/client";

type Props = {
  children: React.ReactNode;
};

export default function SessionProvider({ children }: Props) {
  const router = useRouter();
  const pathname = usePathname();
  const [ready, setReady] = useState(false);

  useEffect(() => {
    let unsub: { unsubscribe: () => void } | null = null;

    const init = async () => {
      const { data: { session } } = await supabase.auth.getSession();
      // Redirect unauthenticated users away from protected routes
      const isAuthPage = pathname?.startsWith("/login");
      if (!session && !isAuthPage) {
        router.replace("/login");
      }
      if (session && isAuthPage) {
        router.replace("/gear");
      }

      const { data } = supabase.auth.onAuthStateChange((event, newSession) => {
        if (event === "SIGNED_IN" && pathname?.startsWith("/login")) {
          router.replace("/gear");
        } else if (event === "SIGNED_OUT") {
          router.replace("/login");
        }
      });
      unsub = data;
      setReady(true);
    };

    init();

    return () => {
      if (unsub) {
        unsub.unsubscribe();
      }
    };
  }, [pathname, router]);

  if (!ready) {
    return <div className="flex items-center justify-center min-h-dvh text-sm text-muted-foreground">Loading…</div>;
  }

  return <>{children}</>;
}